### PR TITLE
Data Deletion Request Framework.md

### PR DESCRIPTION
**Pull request by jaredmoscow**
Data deletion request framework for public comment

### CODE REVIEW

**Comment by asr-enid** [comment]
@jaredmoscow in which form would you want feedback? Review the PR, E-Mail, Issues ?

**Comment by jaredmoscow** [comment]
@asr-enid please email support@iabtechlab.com to submit comments or create Issues - thanks!

**Comment by patmmccann** [comment]
We've noticed we forgot to define this event https://github.com/InteractiveAdvertisingBureau/USPrivacy/blob/0b8debd388fd3a97cfb15136f8232166010c8c29/CCPA/Data%20Deletion%20Request%20Handling.md?plain=1#L28

**Comment by jaredmoscow** [comment]
Closing this PR as the first public comment period has concluded. After working through the first batch of comments, the global privacy working group has entered a second public comment period, which is available on this repo: https://github.com/InteractiveAdvertisingBureau/Data-Subject-Rights/blob/development/Data%20Deletion%20Request%20Framework.md 

Please reference this link to provide comments on April 22, 2024.

**Review by themosthigh621 — APPROVED** [review]

**Pull request closed without merging**
